export type CompanyStatus = "興味あり" | "応募予定" | "応募済み" | "説明会参加" | "書類選考" | "適性検査" | "一次面接" | "二次面接" | "最終面接" | "内定" | "不合格" | "辞退";

export interface Database {
  public: {
    Tables: {
      profiles: { Row: { id: string; display_name: string; school_name: string | null; graduation_year: number | null; created_at: string; updated_at: string }; Insert: { id: string; display_name: string; school_name?: string | null; graduation_year?: number | null }; Update: { display_name?: string; school_name?: string | null; graduation_year?: number | null }; Relationships: [] };
      companies: { Row: { id: string; user_id: string; name: string; industry: string | null; company_type: string | null; job_position: string | null; location: string | null; application_source: string | null; job_url: string | null; corporate_url: string | null; interest_level: number | null; current_status: CompanyStatus; memo: string | null; created_at: string; updated_at: string }; Insert: { user_id: string; name: string; industry?: string | null; company_type?: string | null; job_position?: string | null; location?: string | null; application_source?: string | null; job_url?: string | null; corporate_url?: string | null; current_status?: CompanyStatus; interest_level?: number | null; memo?: string | null }; Update: Partial<Database["public"]["Tables"]["companies"]["Insert"]>; Relationships: [] };
      selection_events: { Row: { id: string; company_id: string; user_id: string; event_type: string; title: string; event_date: string; result: string | null; memo: string | null; created_at: string; updated_at: string }; Insert: { company_id: string; user_id: string; event_type: string; title: string; event_date: string; result?: string | null; memo?: string | null }; Update: Partial<Database["public"]["Tables"]["selection_events"]["Insert"]>; Relationships: [] };
      schedules: { Row: { id: string; company_id: string | null; user_id: string; title: string; schedule_type: string; start_at: string; end_at: string | null; is_deadline: boolean; is_completed: boolean; memo: string | null; created_at: string; updated_at: string }; Insert: { company_id?: string | null; user_id: string; title: string; schedule_type: string; start_at: string; end_at?: string | null; is_deadline?: boolean; is_completed?: boolean; memo?: string | null }; Update: Partial<Database["public"]["Tables"]["schedules"]["Insert"]>; Relationships: [] };
      interview_records: { Row: { id: string; company_id: string; user_id: string; interview_round: string | null; interview_date: string | null; expected_questions: string | null; prepared_answers: string | null; reverse_questions: string | null; actual_questions: string | null; actual_answers: string | null; good_points: string | null; improvement_points: string | null; interviewer_impression: string | null; result: string | null; memo: string | null; created_at: string; updated_at: string }; Insert: { company_id: string; user_id: string; interview_round?: string | null; interview_date?: string | null; expected_questions?: string | null; prepared_answers?: string | null; reverse_questions?: string | null; actual_questions?: string | null; actual_answers?: string | null; good_points?: string | null; improvement_points?: string | null; interviewer_impression?: string | null; result?: string | null; memo?: string | null }; Update: Partial<Database["public"]["Tables"]["interview_records"]["Insert"]>; Relationships: [] };
      company_research: { Row: { id: string; company_id: string; user_id: string; company_features: string | null; main_business: string | null; strengths: string | null; weaknesses: string | null; motivation: string | null; what_to_do_after_joining: string | null; reverse_question_candidates: string | null; concerns: string | null; created_at: string; updated_at: string }; Insert: { company_id: string; user_id: string; company_features?: string | null; main_business?: string | null; strengths?: string | null; weaknesses?: string | null; motivation?: string | null; what_to_do_after_joining?: string | null; reverse_question_candidates?: string | null; concerns?: string | null }; Update: Partial<Database["public"]["Tables"]["company_research"]["Insert"]>; Relationships: [] };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
