"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { companySchema, type CompanyInput } from "@/lib/validations/company";
import { selectionEventSchema, scheduleSchema, type SelectionEventInput, type ScheduleInput } from "@/lib/validations/activity";
import { interviewRecordSchema, companyResearchSchema, type InterviewRecordInput, type CompanyResearchInput } from "@/lib/validations/interview";

type ActionResult = { error?: string; fieldErrors?: Partial<Record<keyof CompanyInput, string>> };
async function authenticatedClient() {
  const supabase = await createClient(); const { data } = await supabase.auth.getClaims(); const userId = data?.claims?.sub;
  if (!userId) throw new Error("UNAUTHORIZED");
  return { supabase, userId };
}
function message(error: { message: string }) { if (error.message.includes("最大100社")) return "登録できる企業は最大100社です。不要な企業を削除してから、もう一度お試しください。"; return "保存に失敗しました。時間をおいてもう一度お試しください。"; }
export async function createCompany(input: CompanyInput): Promise<ActionResult> {
  const parsed = companySchema.safeParse(input); if (!parsed.success) return { fieldErrors: Object.fromEntries(Object.entries(parsed.error.flatten().fieldErrors).map(([key, value]) => [key, value?.[0]])) };
  const { supabase, userId } = await authenticatedClient(); const { error } = await supabase.from("companies").insert({ user_id: userId, name: parsed.data.name, industry: parsed.data.industry, company_type: parsed.data.companyType, job_position: parsed.data.jobPosition, location: parsed.data.location, current_status: parsed.data.currentStatus, interest_level: parsed.data.interestLevel, application_source: parsed.data.applicationSource, job_url: parsed.data.jobUrl, corporate_url: parsed.data.corporateUrl, memo: parsed.data.memo });
  if (error) { console.error("create company", error); return { error: message(error) }; } revalidatePath("/companies"); revalidatePath("/dashboard"); redirect("/companies");
}
export async function updateCompany(id: string, input: CompanyInput): Promise<ActionResult> {
  const parsed = companySchema.safeParse(input); if (!parsed.success) return { fieldErrors: Object.fromEntries(Object.entries(parsed.error.flatten().fieldErrors).map(([key, value]) => [key, value?.[0]])) };
  const { supabase, userId } = await authenticatedClient(); const { error } = await supabase.from("companies").update({ name: parsed.data.name, industry: parsed.data.industry, company_type: parsed.data.companyType, job_position: parsed.data.jobPosition, location: parsed.data.location, current_status: parsed.data.currentStatus, interest_level: parsed.data.interestLevel, application_source: parsed.data.applicationSource, job_url: parsed.data.jobUrl, corporate_url: parsed.data.corporateUrl, memo: parsed.data.memo }).eq("id", id).eq("user_id", userId);
  if (error) { console.error("update company", error); return { error: message(error) }; } revalidatePath("/companies"); revalidatePath(`/companies/${id}`); revalidatePath("/dashboard"); redirect(`/companies/${id}`);
}
export async function deleteCompany(id: string): Promise<ActionResult> {
  const { supabase, userId } = await authenticatedClient(); const { error } = await supabase.from("companies").delete().eq("id", id).eq("user_id", userId); if (error) { console.error("delete company", error); return { error: "削除に失敗しました。時間をおいてもう一度お試しください。" }; } revalidatePath("/companies"); revalidatePath("/dashboard"); redirect("/companies");
}
function validationResult(parsed: { success: false; error: { flatten: () => { fieldErrors: Record<string, string[] | undefined> } } }): ActionResult { return { fieldErrors: Object.fromEntries(Object.entries(parsed.error.flatten().fieldErrors).map(([key, value]) => [key, value?.[0]])) }; }
export async function createSelectionEvent(companyId: string, input: SelectionEventInput): Promise<ActionResult> {
  const parsed = selectionEventSchema.safeParse(input); if (!parsed.success) return validationResult(parsed); const { supabase, userId } = await authenticatedClient(); const { error } = await supabase.from("selection_events").insert({ company_id: companyId, user_id: userId, event_type: parsed.data.eventType, title: parsed.data.title, event_date: new Date(parsed.data.eventDate).toISOString(), result: parsed.data.result || null, memo: parsed.data.memo || null }); if (error) { console.error("create selection event", error); return { error: error.message.includes("最大30件") ? "選考履歴は1社につき最大30件です。" : "選考履歴の登録に失敗しました。" }; } revalidatePath(`/companies/${companyId}`); return {};
}
export async function createSchedule(companyId: string, input: ScheduleInput): Promise<ActionResult> {
  const parsed = scheduleSchema.safeParse(input); if (!parsed.success) return validationResult(parsed); const { supabase, userId } = await authenticatedClient(); const { error } = await supabase.from("schedules").insert({ company_id: companyId, user_id: userId, title: parsed.data.title, schedule_type: parsed.data.scheduleType, start_at: new Date(parsed.data.startAt).toISOString(), end_at: parsed.data.endAt ? new Date(parsed.data.endAt).toISOString() : null, is_deadline: parsed.data.isDeadline, memo: parsed.data.memo || null }); if (error) { console.error("create schedule", error); return { error: error.message.includes("最大30件") ? "予定は1社につき最大30件です。" : "予定の登録に失敗しました。" }; } revalidatePath(`/companies/${companyId}`); revalidatePath("/schedule"); revalidatePath("/dashboard"); return {};
}
export async function updateSchedule(scheduleId: string, input: ScheduleInput): Promise<ActionResult> { const parsed = scheduleSchema.safeParse(input); if (!parsed.success) return validationResult(parsed); const { supabase, userId } = await authenticatedClient(); const { error } = await supabase.from("schedules").update({ title: parsed.data.title, schedule_type: parsed.data.scheduleType, start_at: new Date(parsed.data.startAt).toISOString(), end_at: parsed.data.endAt ? new Date(parsed.data.endAt).toISOString() : null, is_deadline: parsed.data.isDeadline, memo: parsed.data.memo || null }).eq("id", scheduleId).eq("user_id", userId); if (error) { console.error("update schedule", error); return { error: "予定の更新に失敗しました。" }; } revalidatePath("/schedule"); revalidatePath("/dashboard"); return {}; }
export async function toggleScheduleCompleted(scheduleId: string, completed: boolean): Promise<ActionResult> { const { supabase, userId } = await authenticatedClient(); const { error } = await supabase.from("schedules").update({ is_completed: completed }).eq("id", scheduleId).eq("user_id", userId); if (error) { console.error("toggle schedule", error); return { error: "予定の更新に失敗しました。" }; } revalidatePath("/schedule"); revalidatePath("/dashboard"); return {}; }
export async function deleteSchedule(scheduleId: string): Promise<ActionResult> { const { supabase, userId } = await authenticatedClient(); const { error } = await supabase.from("schedules").delete().eq("id", scheduleId).eq("user_id", userId); if (error) { console.error("delete schedule", error); return { error: "予定の削除に失敗しました。" }; } revalidatePath("/schedule"); revalidatePath("/dashboard"); return {}; }
export async function createInterviewRecord(companyId: string, input: InterviewRecordInput): Promise<ActionResult> { const parsed = interviewRecordSchema.safeParse(input); if (!parsed.success) return validationResult(parsed); const { supabase, userId } = await authenticatedClient(); const { error } = await supabase.from("interview_records").insert({ company_id: companyId, user_id: userId, interview_round: parsed.data.interviewRound || null, interview_date: parsed.data.interviewDate ? new Date(parsed.data.interviewDate).toISOString() : null, expected_questions: parsed.data.expectedQuestions, prepared_answers: parsed.data.preparedAnswers, reverse_questions: parsed.data.reverseQuestions, actual_questions: parsed.data.actualQuestions, actual_answers: parsed.data.actualAnswers, good_points: parsed.data.goodPoints, improvement_points: parsed.data.improvementPoints, interviewer_impression: parsed.data.interviewerImpression, result: parsed.data.result || null, memo: parsed.data.memo }); if (error) { console.error("create interview record", error); return { error: error.message.includes("最大10件") ? "面接記録は1社につき最大10件です。" : "面接記録の登録に失敗しました。" }; } revalidatePath(`/companies/${companyId}`); return {}; }
export async function saveCompanyResearch(companyId: string, input: CompanyResearchInput): Promise<ActionResult> { const parsed = companyResearchSchema.safeParse(input); if (!parsed.success) return validationResult(parsed); const { supabase, userId } = await authenticatedClient(); const { error } = await supabase.from("company_research").upsert({ company_id: companyId, user_id: userId, company_features: parsed.data.companyFeatures, main_business: parsed.data.mainBusiness, strengths: parsed.data.strengths, weaknesses: parsed.data.weaknesses, motivation: parsed.data.motivation, what_to_do_after_joining: parsed.data.whatToDoAfterJoining, reverse_question_candidates: parsed.data.reverseQuestionCandidates, concerns: parsed.data.concerns }, { onConflict: "company_id" }); if (error) { console.error("save company research", error); return { error: "企業研究の保存に失敗しました。" }; } revalidatePath(`/companies/${companyId}`); return {}; }
