"use client";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Plus } from "lucide-react";
import { createSelectionEvent } from "@/app/(app)/companies/actions";
import { SELECTION_EVENT_TYPES } from "@/lib/constants/companies";
import { selectionEventSchema, type SelectionEventInput } from "@/lib/validations/activity";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Textarea } from "@/components/ui/textarea";
export function SelectionEventDialog({ companyId }: { companyId: string }) { const [open, setOpen] = useState(false); const [serverError, setServerError] = useState<string>(); const form = useForm<SelectionEventInput>({ resolver: zodResolver(selectionEventSchema), defaultValues: { eventType: "応募", title: "", eventDate: "", result: "", memo: "" } }); async function submit(values: SelectionEventInput) { const result = await createSelectionEvent(companyId, values); if (result?.error) return setServerError(result.error); if (result?.fieldErrors) { Object.entries(result.fieldErrors).forEach(([key, message]) => form.setError(key as keyof SelectionEventInput, { message })); return; } form.reset(); setOpen(false); } return <><Button onClick={() => setOpen(true)}><Plus className="mr-2 size-4" />選考履歴を追加</Button>{open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/30"><form onSubmit={form.handleSubmit(submit)} className="w-full max-w-lg border bg-white p-6 shadow-lg"><h2 className="text-lg font-semibold">選考履歴を追加</h2><div className="mt-5 space-y-4"><Field label="イベント種別"><select {...form.register("eventType")} className="h-10 w-full rounded-md border px-3 text-sm">{SELECTION_EVENT_TYPES.map((value) => <option key={value}>{value}</option>)}</select></Field><Field label="タイトル" error={form.formState.errors.title?.message}><Input {...form.register("title")} placeholder="例：エントリーシートを提出" /></Field><Field label="日付" error={form.formState.errors.eventDate?.message}><Input type="datetime-local" {...form.register("eventDate")} /></Field><Field label="結果" error={form.formState.errors.result?.message}><Input {...form.register("result")} placeholder="例：通過" /></Field><Field label="メモ" error={form.formState.errors.memo?.message}><Textarea {...form.register("memo")} /></Field></div>{serverError && <p className="mt-3 text-sm text-red-600">{serverError}</p>}<div className="mt-6 flex justify-end gap-3"><Button type="button" variant="outline" onClick={() => setOpen(false)}>キャンセル</Button><Button type="submit" disabled={form.formState.isSubmitting}>登録する</Button></div></form></div>}</>; }
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}{error && <p className="text-sm text-red-600">{error}</p>}</div>; }
