"use client";
import { useState } from "react";
import { useForm } from "react-hook-form";
import type { Resolver } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { LoaderCircle } from "lucide-react";
import { createCompany, updateCompany } from "@/app/(app)/companies/actions";
import { COMPANY_STATUSES, COMPANY_TYPES, INTEREST_LABELS } from "@/lib/constants/companies";
import { companySchema, type CompanyInput } from "@/lib/validations/company";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

type Props = { company?: CompanyInput; companyId?: string; companyCount: number };
const defaults: CompanyInput = { name: "", industry: "", companyType: "", jobPosition: "", location: "", currentStatus: "興味あり", interestLevel: 3, applicationSource: "", jobUrl: "", corporateUrl: "", memo: "" };
export function CompanyForm({ company, companyId, companyCount }: Props) {
  const [serverError, setServerError] = useState<string>(); const isEdit = Boolean(companyId);
  const form = useForm<CompanyInput>({ resolver: zodResolver(companySchema) as Resolver<CompanyInput>, defaultValues: company ?? defaults });
  const error = (name: keyof CompanyInput) => form.formState.errors[name]?.message;
  async function submit(values: CompanyInput) { setServerError(undefined); const result = isEdit ? await updateCompany(companyId!, values) : await createCompany(values); if (result?.fieldErrors) Object.entries(result.fieldErrors).forEach(([key, value]) => form.setError(key as keyof CompanyInput, { message: value })); if (result?.error) setServerError(result.error); }
  return <form onSubmit={form.handleSubmit(submit)} className="mx-auto max-w-4xl space-y-6"><div className="flex items-center justify-between border-b pb-4"><div><p className="text-sm text-slate-500">現在の登録数：{companyCount} / 100社</p>{!isEdit && companyCount >= 90 && <p className="mt-1 text-sm text-amber-700">登録上限に近づいています。不要な企業を確認してください。</p>}</div></div><section className="border bg-white"><header className="border-b px-6 py-4"><h2 className="font-semibold">基本情報</h2></header><div className="grid grid-cols-2 gap-5 p-6"><Field label="企業名" error={error("name")}><Input {...form.register("name")} placeholder="例：株式会社JobPath" /></Field><Field label="業界" error={error("industry")}><Input {...form.register("industry")} placeholder="例：IT・ソフトウェア" /></Field><Field label="企業区分" error={error("companyType")}><Select {...form.register("companyType")}><option value="">選択してください</option>{COMPANY_TYPES.map((value) => <option key={value}>{value}</option>)}</Select></Field><Field label="応募職種" error={error("jobPosition")}><Input {...form.register("jobPosition")} placeholder="例：ソフトウェアエンジニア" /></Field><Field label="所在地" error={error("location")}><Input {...form.register("location")} placeholder="例：東京都" /></Field></div></section><section className="border bg-white"><header className="border-b px-6 py-4"><h2 className="font-semibold">選考情報</h2></header><div className="grid grid-cols-2 gap-5 p-6"><Field label="現在の選考状況" error={error("currentStatus")}><Select {...form.register("currentStatus")}>{COMPANY_STATUSES.map((value) => <option key={value}>{value}</option>)}</Select></Field><Field label="志望度" error={error("interestLevel")}><Select {...form.register("interestLevel", { valueAsNumber: true })}>{[1, 2, 3, 4, 5].map((value) => <option key={value} value={value}>{value}：{INTEREST_LABELS[value]}</option>)}</Select></Field><Field label="応募経路" error={error("applicationSource")}><Input {...form.register("applicationSource")} placeholder="例：ナビサイト、紹介" /></Field></div></section><section className="border bg-white"><header className="border-b px-6 py-4"><h2 className="font-semibold">補足情報</h2></header><div className="grid grid-cols-2 gap-5 p-6"><Field label="求人URL" error={error("jobUrl")}><Input {...form.register("jobUrl")} type="url" placeholder="https://" /></Field><Field label="企業ホームページURL" error={error("corporateUrl")}><Input {...form.register("corporateUrl")} type="url" placeholder="https://" /></Field><div className="col-span-2"><Field label="メモ" error={error("memo")}><Textarea {...form.register("memo")} placeholder="選考に関するメモや気になる点を記録できます。" /></Field></div></div></section>{serverError && <p role="alert" className="border border-red-200 bg-red-50 p-3 text-sm text-red-700">{serverError}</p>}<div className="flex justify-end gap-3"><Button type="submit" disabled={form.formState.isSubmitting || (!isEdit && companyCount >= 100)}>{form.formState.isSubmitting && <LoaderCircle className="mr-2 size-4 animate-spin" />}{isEdit ? "更新する" : "企業を登録"}</Button></div></form>;
}
function Field({ label, error, children }: { label: string; error?: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}{error && <p className="text-sm text-red-600">{error}</p>}</div>; }
function Select(props: React.SelectHTMLAttributes<HTMLSelectElement>) { return <select className="h-10 w-full rounded-md border bg-white px-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-blue-100" {...props} />; }
