"use client";
import Link from "next/link";
import { useState } from "react";
import { ArrowLeft, Pencil, Trash2 } from "lucide-react";
import { deleteCompany } from "@/app/(app)/companies/actions";
import { CompanyStatusBadge } from "@/components/companies/company-status-badge";
import { Button } from "@/components/ui/button";
import type { Database } from "@/types/database";
type Company = Database["public"]["Tables"]["companies"]["Row"];
export function CompanyDetailHeader({ company, backHref = "/companies" }: { company: Company; backHref?: string }) { const [confirming, setConfirming] = useState(false); const [error, setError] = useState<string>(); const [deleting, setDeleting] = useState(false); async function remove() { setDeleting(true); const result = await deleteCompany(company.id); if (result?.error) { setError(result.error); setDeleting(false); } } return <><header className="border-b bg-white px-8 py-5"><Link href={backHref} className="mb-4 inline-flex items-center gap-1 text-sm font-medium text-slate-500 hover:text-blue-700"><ArrowLeft className="size-4" />企業一覧へ戻る</Link><div className="flex items-start justify-between"><div><div className="flex items-center gap-3"><h1 className="text-2xl font-semibold">{company.name}</h1><CompanyStatusBadge status={company.current_status} /></div><p className="mt-2 text-sm text-slate-500">{company.job_position ?? "応募職種未設定"}　·　{company.company_type ?? "企業区分未設定"}　·　志望度 {company.interest_level ?? "—"} / 5</p></div><div className="flex gap-2"><Button variant="outline" asChild><Link href={`/companies/${company.id}/edit`}><Pencil className="mr-2 size-4" />編集</Link></Button><Button variant="destructive" onClick={() => setConfirming(true)}><Trash2 className="mr-2 size-4" />削除</Button></div></div></header>{confirming && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/30"><div role="alertdialog" aria-modal="true" className="w-full max-w-md rounded-xl border bg-white p-6 shadow-lg"><h2 className="text-lg font-semibold">この企業を削除しますか？</h2><p className="mt-3 text-sm leading-6 text-slate-600">企業情報に加えて、選考履歴、予定、面接記録、企業研究も削除されます。この操作は元に戻せません。</p>{error && <p className="mt-4 text-sm text-red-600">{error}</p>}<div className="mt-6 flex justify-end gap-3"><Button variant="outline" disabled={deleting} onClick={() => setConfirming(false)}>キャンセル</Button><Button variant="destructive" disabled={deleting} onClick={remove}>{deleting ? "削除中..." : "削除する"}</Button></div></div></div>}</>; }
